---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-project
  name: test-project
  namespace: test-project
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-project
---